### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by kf5upm** [brendena/raspberry-shifter#1]
Getting this error during CMAKE.

CMake Error at CMakeLists.txt:15 (add_subdirectory):
  The source directory

    D:/Workspace/Development/MCU/RaspPi/raspberry-shifter/ps2/atkPico

  does not contain a CMakeLists.txt file.

**Comment by brendena** [comment]
Nice catch.  The problem was the .gitmodules file wasn't added in the repo for some reason?  

If you grab the latest code and do a 
git submodule init
git submodule pull

It should be all good
